### ISSUE TITLE
No suitable formatting

### ISSUE THREAD

**Issue by gtdalp** [microlv/vue-storage-plus#1]
Please add this format: $ls.set(["a", "b", "c"], [a, b, c])
Thank you

**Comment by microlv** [comment]
the feature enhancement has been added and release at 1.0.4
please feel free to have a check
thanks for your support!
@gtdalp

**Comment by gtdalp** [comment]
Nice, thank you very much.

**Comment by gtdalp** [comment]
Nice, thank you very much.
